version: '3.8'
services:

# NGINX Service
  webserver:
    image: nginx:alpine
    container_name: aimoonx-webserver
    restart: always
    tty: true
    ports:
      - "3000:24300"
      - "443:24443"
    volumes:
      - "./:/var/www"
      - "./docker-files/nginx/conf.d/:/etc/nginx/conf.d/"
 
